version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = [
    "angular",
    "react",
    "angularjs",
    "vue"
  ]
  environment = [
    "jquery",
    "mongo",
    "browser",
    "nodejs"
  ]

[[analyzers]]
name = "php"

[[analyzers]]
name = "sql"